version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend/frontend
    container_name: frontend_c
    ports:
      - '80:3000'
    # volumes:
    #   - ./frontend/frontend: /frontend
    #   - ./frontend/node_modules
    stdin_open: true
    tty: true 
    depends_on: 
      - backend
    
