spring:
  application:
    name: AllianceSeedsApi
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/allianceSeeds
    username: ${DATABASE_USERNAME:allianceSeeds_admin}
    password: ${DATABASE_PASSWORD:T00l8ox4}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baselineOnMigrate: true  # Baseline the database
    baselineVersion: 1       # Set baseline version
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/allianceSeeds
    user: ${DATABASE_USERNAME:allianceSeeds_admin}
    password: ${DATABASE_PASSWORD:T00l8ox4}
    schemas: public
    locations: classpath:db/migration


  jpa:
    generate-ddl: true
    hibernate:
      dll-auto: update


  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply@accutrak.co.za
    password: '@ccut0821'
    properties.mail.smtp:
      auth: true
      starttls.enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOACK_ISSUER_URI:https://node.accutrak.co.za/auth/realms/codesmith}  #iss
          jwk-set-uri: ${KEYCLOACK_JWK_SET_URI:https://node.accutrak.co.za/auth/realms/codesmith/protocol/openid-connect/certs}
#          issuer-uri: https://node.accutrak.co.za/auth/realms/accutrak  #
#          jwk-set-uri: https://node.accutrak.co.za/auth/realms/accutrak/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: allianceseeds
      principal-attribute: principal_username

logging:
  level:
    root: INFO
#    org.springframework.security: INFO # Optionally, set INFO level for specific packages

  file:
    name: logs/app.log
    max-size: 10MB
    max-history: 30

  # Optional: Configure log file patterns (if you want to include date in filenames)
  log:
    pattern:
      file: "logs/app-%d{yyyy-MM-dd}.log" # Pattern for rolling log files
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" # Console log patte

server:
  port: ${SERVER_PORT:9091}
#  tomcat:
#    max-http-post-size: 20000000
  servlet:
    context-path: /api/v1/
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB







