# Generated by Django 4.2.2 on 2023-06-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('prodCode', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('Cricket', 'Cricket'), ('Hockey', 'Hockey'), ('Athletics', 'Athletics'), ('Soccer', 'Soccer')], max_length=10)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
