# Generated by Django 4.2.2 on 2023-07-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cricket', 'Cricket'), ('Hockey', 'Hockey'), ('Athletics', 'Athletics'), ('Soccer', 'Soccer'), ('Rugby', 'Rugby'), ('Golf', 'Golf'), ('Tennis', 'Tennis'), ('Horse_Riding', 'Horse_Riding'), ('Other', 'Other')], max_length=20),
        ),
    ]
