# Generated by Django 4.2.2 on 2023-07-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_shoes_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=10)),
                ('cell', models.CharField(max_length=10)),
            ],
        ),
    ]
