# Generated by Django 4.2.2 on 2023-07-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pendingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingproduct',
            name='image1',
            field=models.ImageField(blank=True, upload_to='pending_images'),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='image2',
            field=models.ImageField(blank=True, upload_to='pending_images'),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='image3',
            field=models.ImageField(blank=True, upload_to='pending_images'),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='image4',
            field=models.ImageField(blank=True, upload_to='pending_images'),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='image5',
            field=models.ImageField(blank=True, upload_to='pending_images'),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='image6',
            field=models.ImageField(blank=True, upload_to='pending_images'),
        ),
    ]
