# Generated by Django 4.2.2 on 2023-07-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pendingproduct_image1_pendingproduct_image2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingProduct',
        ),
    ]
