# Generated by Django 4.2.2 on 2023-12-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=120)),
                ('buyerName', models.CharField(max_length=120)),
                ('cell', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=120)),
                ('prodCode', models.CharField(max_length=10)),
                ('price', models.FloatField(default=9999)),
                ('address', models.CharField(max_length=120)),
                ('receiptNo', models.CharField(max_length=120)),
            ],
        ),
    ]
