# Generated by Django 4.2.2 on 2023-12-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptNo', models.CharField(max_length=120)),
                ('buyerName', models.CharField(max_length=120)),
                ('cell', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='sold',
            name='receipt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.receipt'),
        ),
    ]
