# Generated by Django 4.2.2 on 2023-12-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_receipt_sold_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='totalPrice',
            field=models.FloatField(default=9999),
        ),
    ]
