# Generated by Django 4.2.2 on 2024-07-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
