# Generated by Django 4.2.2 on 2024-07-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_image2_product_image3_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
