# Generated by Django 4.2.2 on 2024-07-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_product_image2_alter_product_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cricket', 'Cricket'), ('Hockey', 'Hockey'), ('Athletics', 'Athletics'), ('Soccer', 'Soccer'), ('Rugby', 'Rugby'), ('Golf', 'Golf'), ('Tennis', 'Tennis'), ('Horse_Riding', 'Horse_Riding'), ('Other', 'Other'), ('Cycling', 'Cycling'), ('Trainers', 'Trainers')], max_length=20),
        ),
    ]
