# Generated by Django 4.2.2 on 2024-07-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodCode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
